version: '3.4'

networks:
  backend:

services:
  blogapi:
    container_name: blog-api
    image: ${DOCKER_REGISTRY-}blogapi
    depends_on:
      - "blogdb"
    ports: 
      - "18004:80"
    build:
      context: .
      dockerfile: BlogAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=blogdb;Port=5432;Database=ITBlogDb; IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - backend

  blogdb:
    container_name: blog-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ITBlogDb
    ports:
      - "5433:5432"
    restart: always
    networks:
      - backend

  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
    # rabbitmq instant
      - '5672:5672'
    # web interface
      - '15672:15672'
    networks:
      - backend

