name: BlogAPI, build - test - dockerpush, deploy azure workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore BlogAPI/BlogAPI.csproj
    - name: Build
      run: dotnet build BlogAPI/BlogAPI.csproj --no-restore
    - name: Test
      run: dotnet test ./BlogAPI.sln --configuration Release

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.2
      with:
        image: onurinc/blogapi
        tags: v1, latest, ${{ github.sha }}
        registry: docker.io
        dockerfile: BlogAPI/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
        # Deploy docker hub image to azure with publish auth
      - name: deploy to azure
        uses: azure/webapps-deploy@v2
        with:
            app-name: 'ITBlogAPI'
            publish-profile: ${{ secrets.AZURE_APPSERVICE_PUBLISHPROFILE }}
            images: 'index.docker.io/${{ secrets.DOCKER_USERNAME }}/blogapi:${{ github.sha }}'       
